export const REQUEST_STATUS = {
  IDLE: 'IDLE',
  LOADING: 'LOADING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
};

export const USER_TYPE = {
  CONTRACTOR: 'contractor',
  OWNER: 'owner'
}

export const FETCH_MAP_MARKERS_LOADING = 'FETCH_MAP_MARKERS_LOADING';
export const FETCH_MAP_MARKERS_SUCCESS = 'FETCH_MAP_MARKERS_SUCCESS';
export const FETCH_MAP_MARKERS_ERROR = 'FETCH_MAP_MARKERS_ERROR';

export const UPDATE_VIEWPORT = 'UPDATE_VIEWPORT';

export const FETCH_USER_LOADING = 'FETCH_USER_LOADING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCH_USERS_LOADING = 'FETCH_USERS_LOADING';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_USER_CLEANUP = 'FETCH_USER_CLEANUP';
